<a href="https://colab.research.google.com/github/HajarFazillah/24-1_NumericalAnalysis/blob/main/4_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy  as np  # 기본 모듈이 아니므로 설치 필요!!
# numpy : number python
# shortform using it 'as np'

```sum()```  # 기본 내장 함수

```np.sum()```  # numpy 라이브러리에서 가져온 함수

In [ ]:
list123 = [1,2,3]

In [ ]:
np.array(list123)

array([1, 2, 3])

In [ ]:
range(1,4)

range(1, 4)

In [ ]:
np.array(range(1,4))  # cf. list(range(1,4))
# show the type

array([1, 2, 3])

In [ ]:
print(np.array(range(1,4)))

[1 2 3]


In [ ]:
np.arange(4) # numpy array range

array([0, 1, 2, 3])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [ ]:
#list와 array 차이 : 요소 구분 표시 - ',' 와 ' '
# hwo to compare list vs array (check how the output looks like)
# list (shows comma, in between range components)
# array (shows ' ', blank space in between the range components)

list_1=[0,0,0,0]
print(list_1)

arr_1=np.ones([4])  # [4] - 1차원 배열 4개, float타입 원소값 1
#  why does it show . point in between? bcs of float type 1.0 - without the 0
print(arr_1)

[0, 0, 0, 0]
[1. 1. 1. 1.]


In [ ]:
print(list_1*3)
print(arr_1*3)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[3. 3. 3. 3.]


In [ ]:
list_2 = [1,1]
arr_2 = [1,2,3,4]

print(list_1+list_2)
print(arr_1 + arr_2)

[0, 0, 0, 0, 1, 1]
[2. 3. 4. 5.]


In [ ]:
c = [7]

print(list_1+ c)
print(arr_1 + c)

[0, 0, 0, 0, 7]
[8. 8. 8. 8.]


In [ ]:
d = 10


# print(list_1+ d)  # type이 달라서 + 연산 오류
print(arr_1 + d)

[11. 11. 11. 11.]


In [ ]:
print(arr_1+list_2)
# 생각보다 array 융통성이 없음

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
print(np.zeros([2,3]))
#  row, col (r,c))

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
zeros=np.zeros([2,4,3], dtype=np.float64)
# group, row, col (g,r,c)
print(zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
print(np.array([1,2,'A',True]))
# list 와 다르게, array는 각 요소의 타입이 통일되어야한다.
# list 장점 - can put everything in any form
# array 특징 - must be on its own

['1' '2' 'A' 'True']


In [ ]:
# arr_2[0]
arr_2[0][1]

2

In [ ]:
arr_2 = np.array([[1,2],[3,4],[5,6]])

print(len(arr_2)) # length of arr_2 = 3
print(arr_2.ndim) # dimension of arr_2 = 2 [1,2]

3
2


In [ ]:
print(np.random.rand(3,5))
# no need to import random separately, numpy has its own random function

[[0.67416853 0.40171699 0.38253671 0.54128379 0.96982904]
 [0.6575075  0.74894867 0.51882796 0.88011321 0.75334887]
 [0.62714944 0.11431303 0.55590794 0.65728203 0.90028365]]


In [ ]:
a1 = np.array([1,2,2,3,4,5])

In [ ]:
b1 = a1.reshape(2,3)
# case: i want to organise neatly into 2 rows, 3 columns
# use the reshape function to organise

print(b1)

[[1 2 2]
 [3 4 5]]


In [ ]:
b1[0]

array([1, 2, 2])

In [ ]:
c1 = a1.reshape(3,2)

print(c1)

[[1 2]
 [2 3]
 [4 5]]


In [ ]:
x = np.arange(9.).reshape(3, 3)
# because 9. is written, it will be in float type

print(x)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [ ]:
x.T # .T - transpose the matrix 선형대수학
# x.transpose()

array([[0., 3., 6.],
       [1., 4., 7.],
       [2., 5., 8.]])

In [ ]:
# 주식가격 자료
stocks = np.array( [140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22])

print(stocks)

[140.49   0.97  40.68  41.53  55.7   57.21  98.2   99.19 109.96 111.47
  35.71  36.27  87.85  89.11  30.22]


In [ ]:
len(stocks)

15

In [ ]:
# 영업일 5일 기준으로 보기
# stocks = stocks.reshape(3,5)
# stocks = stocks.reshape(3, -1)
stocks = stocks.reshape(-1,5)

print(stocks)

[[140.49   0.97  40.68  41.53  55.7 ]
 [ 57.21  98.2   99.19 109.96 111.47]
 [ 35.71  36.27  87.85  89.11  30.22]]


In [ ]:
# 주식가격의 변동이 1보다 크면 변동값을 담고, 변동이 30이하이면 0을 갖는 array
changes1=np.where(np.abs(stocks[1]-stocks[0])>30.00, stocks[1]-stocks[0], 0)
changes2=np.where(np.abs(stocks[2]-stocks[1])>30.00, stocks[2]-stocks[1], 0)
# .where - stocks[1] the 2nd week, if it is above 30.00,

print('changes1: ',changes1)
print('changes2: ',changes2)

changes1:  [-83.28  97.23  58.51  68.43  55.77]
changes2:  [  0.   -61.93   0.     0.   -81.25]


In [ ]:
# ------배열집계
# mean(), median(), sum(), std(), min(), max()

print('np.mean(np.arange(1,11)', np.mean(np.arange(1, 11)))
print('np.median(np.array(1,2,3,4, 9,9,10))', np.median(np.array([1, 2, 3, 4, 9, 9, 9, 10])))
print('np.std(np.array(1,2,3,4, 9,9,10))', np.std(np.array([1, 2, 3, 4, 9, 9, 9, 10])))

np.mean(np.arange(1,11) 5.5
np.median(np.array(1,2,3,4, 9,9,10)) 6.5
np.std(np.array(1,2,3,4, 9,9,10)) 3.4798527267687636
